---
# Double-check. See redundant task in commdata for more info.
# TODO: Rotate secrets now that this check is in place
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

- name: Install prosody
  apt: name=prosody

- name: "Don't install extra prosody modules -- vendored in instead for consistent and recent versions"
  apt:
    name: prosody-modules
    state: absent
  notify: Restart prosody

- name: Directory for Prosody modules
  file:
    state: directory
    path: "/opt/commapps/prosody/modules/"

- name: Install Prosody modules
  synchronize:
    src: "{{ role_path }}/files/prosody/modules/"
    dest: "/opt/commapps/prosody/modules/"

- name: Directory for scripts
  file:
    state: directory
    path: "/opt/commapps/prosody/scripts/"

- name: Setup-helper script
  copy:
    src: "{{ role_path }}/files/keygen/generate-tls-key-csr.sh"
    dest: "/opt/commapps/prosody/scripts/generate-tls-key-csr.sh"
    mode: 0755

- name: Directory for Jabber data in general
  file:
    state: directory
    path: /srv/commdata/jabber
    owner: prosody
    group: prosody
    mode: 0750

# cert oracle depends on main jabber dir
- include: cert-oracle.yml

- name: Directory for Prosody data
  file:
    state: directory
    path: /srv/commdata/jabber/data
    owner: prosody
    group: prosody
    mode: 0750

- name: Directory for Jabber TLS secrets
  file:
    state: directory
    path: /srv/commdata/jabber/tls
    owner: prosody
    group: prosody
    mode: 0750

- name: Create TLS private key and CSR
  command: /opt/commapps/prosody/scripts/generate-tls-key-csr.sh appux.com
  args:
    creates: "/srv/commdata/jabber/tls/appux.com.csr.pem"
  register: jabber__csr_created

- name: Give instructions if CSR and key were created
  debug:
    msg:
    - "First-time setup for appux.com:"
    - "» Cancel this ansible run and log into the server"
    - "» Copy /srv/commdata/jabber/tls/appux.com.csr.pem to NFSN"
    - "» Run the cert-oracle script on NFSN"
    - "» Run receiver on the server: /srv/commdata/jabber/cert-oracle/recv-ssl-certs.sh appux.com"
    verbosity: 0
  when: jabber__csr_created.changed and not ansible_check_mode

- name: Pause for manual intervention when key and CSR created
  pause:
  when: jabber__csr_created.changed and not ansible_check_mode

# TODO: Use rsync module to convey the conf.d files all at once

- name: Directories for supporting configs
  file:
    state: directory
    path: /etc/prosody/conf.d/vhosts

- name: "Supporting prosody configs: brainonfire vhost"
  copy:
    src: "{{ role_path }}/files/prosody/vhosts/brainonfire.net.cfg.lua"
    dest: /etc/prosody/conf.d/vhosts/brainonfire.net.cfg.lua
  notify: Restart prosody

- name: "Supporting prosody configs: appux vhost"
  copy:
    src: "{{ role_path }}/files/prosody/vhosts/appux.com.cfg.lua"
    dest: /etc/prosody/conf.d/vhosts/appux.com.cfg.lua
  notify: Restart prosody

- name: Main prosody config
  copy:
    src: "{{ role_path }}/files/prosody/prosody.cfg.lua"
    dest: /etc/prosody/prosody.cfg.lua
  notify: Restart prosody
