---
# Double-check. See redundant task in commdata for more info.
# TODO: Rotate secrets now that this check is in place
- name: "Confirm that commdata is mounted (for prosody data)"
  shell: mountpoint /srv/commdata
  changed_when: False


#== Software ==#

- name: Install prosody
  apt: name=prosody

- name: "Directory for Prosody modules"
  file:
    state: directory
    path: /opt/commapps/prosody/modules

- name: "Install Prosody modules"
  synchronize:
    src: "{{ role_path }}/files/prosody/modules/"
    dest: "/opt/commapps/prosody/modules/"

- name: "Don't install extra prosody modules -- vendored in instead for consistent and recent versions"
  apt:
    name: prosody-modules
    state: absent
  notify: Restart prosody


#== Directory structure ==#

- name: "Directory for scripts"
  file:
    state: directory
    path: /opt/commapps/prosody/scripts

- name: "Directory for Jabber data in general"
  file:
    state: directory
    path: /srv/commdata/jabber

- name: "Directory for Prosody data"
  file:
    state: directory
    path: /srv/commdata/jabber/data
    owner: prosody
    mode: u=rwx,g=,o=

- name: "Directory for Jabber TLS secrets"
  file:
    state: directory
    path: /srv/commdata/jabber/tls
    owner: prosody
    group: prosody
    mode: u=rwx,g=,o=


#== Certificate management ==#

- name: "TLS key generator"
  copy:
    src: "{{ role_path }}/files/create-tls-key.sh"
    dest: /opt/commapps/prosody/scripts/create-tls-key.sh
    mode: preserve

- name: "CSR generator"
  copy:
    src: "{{ role_path }}/files/create-csr.sh"
    dest: /opt/commapps/prosody/scripts/create-csr.sh
    mode: preserve

- name: "Certificate downloader script"
  copy:
    src: "{{ role_path }}/files/fetch-ssl-cert.sh"
    dest: /opt/commapps/prosody/scripts/fetch-ssl-cert.sh
    mode: preserve

- name: "Create log file with correct permissions for certificate downloader"
  file:
    path: /var/log/jabber-cert-updater.log
    owner: prosody
    group: prosody
    # This is required in order to ensure the file is *present* and
    # also gets correct mode/owner, but doesn't get touched if already
    # present. Thanks to https://github.com/ansible/ansible/issues/7490
    state: touch
    modification_time: preserve
    access_time: preserve

- name: "Rotate logs from certificate downloader"
  copy:
    content: |
      /var/log/jabber-cert-updater.log {
        monthly
        rotate 4
        missingok
        create prosody prosody
      }
    dest: /etc/logrotate.d/jabber-cert-updater

- name: "Cron job to download certificates"
  template:
    src: "{{ role_path }}/files/fetch-ssl-cert.cron.j2"
    dest: /etc/cron.d/jabber-cert-updater

- name: "Per-domain TLS setup"
  include_tasks: cert-setup.yml
  loop: "{{ jabber__vhosts }}"


#== Prosody configuration ==#

# TODO: Use rsync module to convey the conf.d files all at once

- name: "Virtualhosts for the various domains"
  synchronize:
    src: "{{ role_path }}/files/prosody/vhosts/"
    dest: /etc/prosody/conf.d/vhosts/
  notify: Restart prosody

- name: "Main prosody config"
  copy:
    src: "{{ role_path }}/files/prosody/prosody.cfg.lua"
    dest: /etc/prosody/prosody.cfg.lua
  notify: Restart prosody
