---
- name: Install prosody
  apt: name=prosody

- name: "Don't install extra prosody modules -- vendored in instead for consistent and recent versions"
  apt:
    name: prosody-modules
    state: absent
  notify: Restart prosody

- name: Directory for Prosody modules
  file:
    state: directory
    path: "/opt/commapps/prosody/modules/"

- name: Install Prosody modules
  synchronize:
    src: "{{ role_path }}/files/prosody/modules/"
    dest: "/opt/commapps/prosody/modules/"

- name: Directory for Jabber data in general
  file:
    state: directory
    path: /srv/commdata/jabber
    owner: prosody
    group: prosody
    mode: 0750

# cert oracle depends on main jabber dir
- include: cert-oracle.yml

- name: Directory for Prosody data
  file:
    state: directory
    path: /srv/commdata/jabber/data
    owner: prosody
    group: prosody
    mode: 0750

- name: Directory for Jabber TLS secrets
  file:
    state: directory
    path: /srv/commdata/jabber/tls
    owner: prosody
    group: prosody
    mode: 0750

# TODO: Write: brainonfire.net.key parsni.ps.key
# TODO: Demand presence of brainonfire.net.chain.pem parsni.ps.chain.pem (prompt to run cert-oracle)

# TODO: Use rsync module to convey the conf.d files all at once

- name: Directories for supporting configs
  file:
    state: directory
    path: /etc/prosody/conf.d/vhosts

- name: "Supporting prosody configs: brainonfire vhost"
  copy:
    src: "{{ role_path }}/files/prosody/vhosts/brainonfire.net.cfg.lua"
    dest: /etc/prosody/conf.d/vhosts/brainonfire.net.cfg.lua
  notify: Restart prosody

- name: "Supporting prosody configs: parsnips vhost"
  copy:
    src: "{{ role_path }}/files/prosody/vhosts/parsni.ps.cfg.lua"
    dest: /etc/prosody/conf.d/vhosts/parsni.ps.cfg.lua
  notify: Restart prosody

- name: Main prosody config
  copy:
    src: "{{ role_path }}/files/prosody/prosody.cfg.lua"
    dest: /etc/prosody/prosody.cfg.lua
  notify: Restart prosody
