---
# Double-check. See redundant task in commdata for more info.
# TODO: Rotate secrets now that this check is in place
- name: "Confirm that commdata is mounted (for sandstorm data)"
  shell: mountpoint /srv/commdata
  changed_when: False

# ----

#== Cert config ==#

- name: "Certificate config for Sandstorm and sites"
  copy:
    content: "{{ item.config | to_nice_json }}"
    dest: "/opt/commapps/certbot/domains.d/{{ item.filename }}"
  loop:
    # Main Sandstorm site
    - filename: sandstorm-main.json
      config:
        sub: sandstorm
        base: appux.com
        wild: true
    # Certificate config for integration test site for Spelunk's WebDAV support
    - filename: sandstorm-spelunk-webdav-integration-test.json
      config:
        sub: spelunk-webdav-testing
        base: spidersge.org
        wild: false
  notify: "certs config update"

#== Sandstorm nginx ==#

- name: Sandstorm nginx configuration
  template:
    src: nginx-sites/sandstorm.conf.j2
    dest: /etc/nginx/sites-available/sandstorm.conf
  notify: nginx reload config

- name: Enable nginx configuration
  file:
    src: /etc/nginx/sites-available/sandstorm.conf
    dest: /etc/nginx/sites-enabled/sandstorm.conf
    state: link
  notify: nginx reload config


#== Sandstorm itself ==#

- name: "A place for sandstorm scripts"
  file:
    state: directory
    path: /opt/commapps/sandstorm
    owner: root
    group: root
    mode: 0755

- name: "Installer script"
  copy:
    src: "{{ role_path }}/files/sandstorm/install.sh"
    dest: /opt/commapps/sandstorm/install.sh
    mode: 0755

- name: "Install Sandstorm"
  shell: /opt/commapps/sandstorm/install.sh /srv/commdata/sandstorm
  args:
    creates: /srv/commdata/sandstorm

- name: "Sandstorm config file"
  template:
    src: "{{ role_path }}/templates/sandstorm/sandstorm.conf.j2"
    dest: "/srv/commdata/sandstorm/sandstorm.conf"
  notify: restart sandstorm

- name: "Ensure sandstorm is running"
  service:
    name: sandstorm
    enabled: yes
    state: started


#== Individual sites hosted in grains ==#

- name: "Sites hosted in grains"
  include_tasks: grain_site.yml
  loop:
    - purpose: "Spelunk's WebDAV integration test server"
      domain: spelunk-webdav-testing.spidersge.org
