# Golang package version and hash, from https://golang.org/dl/
# Use the linux-amd64.tar.gz packages.
matrix__deployments:
  staging:
    user: stg_dendrite
    service_name: stg_dendrite

    data_dir: /srv/commdata/stg_matrix

    pg:
      user: stg_dendrite
      password: "{{ vault_matrix__stg_postgres_password }}"
      db: stg_dendrite
      tablespace: stg_commdata_dendrite

    domain_host: m.staging.appux.com
    domain_identity: staging.appux.com

    root_url_redirect: https://www.appux.com/matrix.html

    certificates:
      - filename: stg_matrix-sub.json
        config:
          sub: m.staging
          base: appux.com
          wild: false

    golang_version: "1.17.3"
    golang_archive_sha256: "550f9845451c0c94be679faf116291e7807a8d78b43149f9506c1b15eb89008c"

    dendrite_repo_url: "https://github.com/matrix-org/dendrite"
    dendrite_version: "v0.5.1"
    dendrite_commit_sha1: "e81ef1649b468126a88a5ccce925f4e4ac865bf4"

    dendrite_listen_port: 7008

    signing_key: "{{ vault_matrix__stg_signing_key }}"
    registration_shared_secret: "{{ vault_matrix__stg_registration_shared_secret }}"

    regui:
      user: stg_matreg
      listen_port: 7009
      admin_password: "{{ vault_matrix__stg_regui_admin_password }}"
      service_name: stg_matrix-registration


  production:
    # OS user account
    user: dendrite

    # systemd service name
    service_name: dendrite

    data_dir: /srv/commdata/matrix

    pg:
      user: dendrite
      # Postgres DB user password for dendrite user account.
      # Must be safe for URL, SQL, and YAML.
      #
      # Set 2021-03-06 to a diceware phrase with no spaces.
      password: "{{ vault_matrix__prod_postgres_password }}"
      db: dendrite
      tablespace: commdata_dendrite

    # "Real" domain name (hosting the server)
    domain_host: matrix.appux.com
    # Domain name used in server identity (in user IDs, etc.)
    domain_identity: appux.com

    root_url_redirect: https://www.appux.com/matrix.html

    certificates:
      - filename: matrix-sub.json
        config:
          sub: matrix
          base: appux.com
          wild: false

    # Dendrite 0.5.0 says it needs Golang >= 1.15 for compilation
    golang_version: "1.17.3"
    golang_archive_sha256: "550f9845451c0c94be679faf116291e7807a8d78b43149f9506c1b15eb89008c"

    # Dendrite version, from https://github.com/matrix-org/dendrite/tags
    dendrite_repo_url: "https://github.com/matrix-org/dendrite"
    dendrite_version: "v0.5.1"
    dendrite_commit_sha1: "e81ef1649b468126a88a5ccce925f4e4ac865bf4"

    dendrite_listen_port: 8008

    # Generated 2021-03-06 (key ID ed25519:dWfnyY) on toster:
    #   (cd /srv/commdata/DATA_DIR/dendrite; sudo -u USER bin/current/generate-keys --private-key tmp_key.pem)
    # after running playbook to point of building dendrite and symlinking
    # the installation.
    signing_key: "{{ vault_matrix__prod_signing_key }}"

    # Shared secret used to enable registration. Not revealed to user --
    # this is shared between Dendrite and matrix-registration.
    # Must be safe for use in a YAML string.
    #
    # - 2021-09-25: Set to four random dictionary words joined by hyphens.
    registration_shared_secret: "{{ vault_matrix__prod_registration_shared_secret }}"


    regui:
      # OS user account
      user: matreg

      listen_port: 8009

      # Used to authenticate to registration UI's admin API (token revocation, etc.)
      # Must be safe for use in a YAML or Bash string and not contain whitespace.
      #
      # - 2021-09-25: Set to four random dictionary words joined by hyphens.
      admin_password: "{{ vault_matrix__prod_regui_admin_password }}"

      service_name: matrix-registration
