# Dendrite 0.5.0 says it needs Golang >= 1.15 for compilation

# Golang package version and hash, from https://golang.org/dl/
# Use the linux-amd64.tar.gz packages.
matrix__golang_version: "1.17.1"
matrix__golang_archive_sha256: "dab7d9c34361dc21ec237d584590d72500652e7c909bf082758fb63064fca0ef"

# Dendrite version, from https://github.com/matrix-org/dendrite/tags
matrix__dendrite_repo_url: "https://github.com/matrix-org/dendrite"
matrix__dendrite_version: "v0.5.0"
matrix__dendrite_commit_sha1: "037ff4fb2364cbee7a3a9a856cd2a711f5398682"

matrix__dendrite_listen_port: 8008

# Generated 2021-03-06 (key ID ed25519:dWfnyY) on toster as dendrite user with command:
#   (cd /srv/commdata/matrix/dendrite; bin/current/generate-keys --private-key matrix_key.pem)
# after running playbook to point of building dendrite and symlinking
# the installation.
matrix__signing_key: "{{ vault_matrix__signing_key }}"

# Shared secret used to enable registration. Not revealed to user --
# this is shared between Dendrite and matrix-registration.
# Must be safe for use in a YAML string.
#
# - 2021-09-25: Set to four random dictionary words joined by hyphens.
matrix__registration_shared_secret: "{{ vault_matrix__registration_shared_secret }}"

# Postgres DB user password for dendrite user account.
# Must be safe for URL, SQL, and YAML.
#
# Set 2021-03-06 to a diceware phrase with no spaces.
matrix__postgres_password: "{{ vault_matrix__postgres_password }}"


matrix__regui_listen_port: 8009

# Used to authenticate to registration UI's admin API (token revocation, etc.)
# Must be safe for use in a YAML or Bash string and not contain whitespace.
#
# - 2021-09-25: Set to four random dictionary words joined by hyphens.
matrix__regui_admin_password: "{{ vault_matrix__regui_admin_password }}"
