---
# All hosts get the common setup
- hosts: all
  remote_user: root
  roles:
    - common

# murphy is a Raspberry Pi
- hosts: murphy.internal
  remote_user: root
  roles:
    - supervisor
    - dyndns

# toster is a laptop
- hosts: toster.internal
  remote_user: root
  roles:
    - laptop
    - role: matrix
      matrix__cfg: "{{ matrix__deployments.production }}"
    - role: matrix
      matrix__cfg: "{{ matrix__deployments.staging }}"
    - role: sandstorm
      sandstorm_base_domain: sandstorm.appux.com
    - jabber
