---

# First time setup:
#
# - Format a thumb drive with a GUID partition table (GPT)
# - Create one partition: ext4, label "not-an-hsm"
# - Run `sudo blkid /dev/sdb1` to find PARTUUID
# - Create //host_vars/$HOST.yml with contents:
#     ---
#     commdata__key_partuuid: $PARTUUID
# - TODO instructions on partitioning main drive
# - Find partition UUID for logical partition used for LUKS, and add it
#   to the host var file:
#     commdata__luks_partuuid: $PARTUUID
# - Set host variables `commdata__zfs` and `commdata__lvm` (at most one as True)
#   depending on which one will be used. ZFS playbook is not supported on some
#   architectures, such as ARM (Raspberry Pi).

- name: "Fail if incompatible FS settings"
  fail:
    msg: "At most one of ZFS and LVM can be selected"
  when: commdata__zfs and commdata__lvm

- include: luks.yml
- include: zfs.yml
  when: commdata__zfs == True
- include: lvm.yml
  when: commdata__lvm == True
