---

# First time setup:
#
# - Format a thumb drive with a GUID partition table (GPT)
# - Create one partition: ext4, label "not-an-hsm"
# - Run `sudo blkid /dev/sdb1` to find PARTUUID
# - Create //host_vars/$HOST.yml with contents:
#     ---
#     commdata__key_partuuid: $PARTUUID
# - TODO instructions on partitioning main drive
# - Find partition UUID for logical partition used for LUKS, and add it
#   to the host var file:
#     commdata__luks_partuuid: $PARTUUID

- include: migration_cleanup.yml
- include: luks.yml
- include: zfs.yml
  when: commdata__zfs == True
