---

# First time setup:
#
# - Format a thumb drive with a GUID partition table (GPT)
# - Create one partition: ext4, label "not-an-hsm"
# - Run `sudo blkid /dev/sdb1` to find PARTUUID
# - Create //host_vars/$HOST.yml with contents:
#     ---
#     commdata__key_partuuid: $PARTUUID
# - TODO instructions on partitioning main drive
# - Find partition UUID for logical partition used for LUKS, and add it
#   to the host var file:
#     commdata__luks_partuuid: $PARTUUID

- include: luks.yml
- include: lvm.yml

# Make sure that no matter how the partition was set up, it is
# properly mounted now. Other roles that rely on the commdata role are
# going to be writing secrets here and need to be sure that it's the
# encrypted partition, not the bare mountpoint.
#
# Other roles may wish to include this directive at the top of their
# tasks as well, besides including commdata as a dependency role in
# their meta/main.yml.
#
# Lack of this directive has caused secrets to be written to disk
# unencrypted before, thanks to a mis-written systemd service file.
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

- name: Directory for caches
  file:
    state: directory
    path: /srv/commdata/cache
