---
- name: "Migration: Disable ZFS mount service"
  service:
    name: commdata-fs
    enabled: no
    state: stopped

- name: "Migration: Systemd unit file for mounting ZFS"
  file:
    state: absent
    path: /etc/systemd/system/commdata-fs.service
  register: commdata__zfs_service_file

- name: Reload systemd config if zfs unit file changed
  command: systemctl daemon-reload
  when: commdata__zfs_service_file.changed

- name: "Migration: Remove ZFS scripts - unmount"
  file:
    state: absent
    path: /opt/commapps/encfs/zfs/unmount.sh

- name: "Migration: Remove ZFS scripts - mount"
  file:
    state: absent
    path: /opt/commapps/encfs/zfs/mount.sh

- name: "Migration: Remove ZFS scripts - dir"
  file:
    state: absent
    path: /opt/commapps/encfs/zfs

- name: "Migration: Destroy ZFS pool in encrypted partition"
  shell: zpool import commdata && zpool destroy commdata
  failed_when: False

- name: "Migration: Stop zfs-fuse"
  service:
    name: zfs-fuse
    enabled: no
    state: stopped

- name: "Migration: Remove ZFS"
  apt:
    name: zfs-fuse
    state: absent
