---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- name: "Directory for supervisor data"
  file:
    state: directory
    path: /srv/commdata/supervisor


#== Backups maintenance ==#

- name: "Create backups user with few permissions"
  user:
    name: backups
    system: yes

- name: "Directory for backups maintenance data"
  file:
    state: directory
    path: /srv/commdata/supervisor/backups
    owner: backups
    mode: u=rx,g=,o=

- name: "Directory for each machine's data"
  file:
    state: directory
    path: "/srv/commdata/supervisor/backups/{{ item.name }}"
    owner: backups
    mode: u=rx,g=,o=
  with_items: "{{ supervisor__hosts }}"

- name: "Migration to remove: Each machine's encrypted Tarsnap key"
  file:
    state: absent
    path: "/srv/commdata/supervisor/backups/{{ item.name }}/tarsnap-full.enc.key"
  with_items: "{{ supervisor__hosts }}"
  no_log: true

- name: "Migration to remove: Each machine's Tarsnap cache directory"
  file:
    state: absent
    path: "/srv/commdata/supervisor/backups/{{ item.name }}/cache"
  with_items: "{{ supervisor__hosts }}"

# TODO: Split out "borg" role from "backups" that just installs borg.
# Then the supervisor role can depend on borg, but not actually get
# backups installed. (I'm not sure the supervisor will need backups,
# and I don't like the idea of shipping sensitive credentials up to
# the cloud, even encrypted, if not absolutely necessary.)
