---

# Fundamental setup

- name: Root ssh folder
  file:
    state: directory
    path: "/root/.ssh"
    owner: root
    group: root
    mode: 0700

- name: Trusted Ansible key
  copy:
    src: "{{ role_path }}/files/id_ansible_appux.pub"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0644

# Standardize sources

- name: "Require setting a known host type"
  fail:
    msg: "Variable common__host_type not set to a supported value"
  when: common__host_type != "rpi" and common__host_type != "stock"

- name: "Install Raspberry Pi sources - main"
  copy:
    src: "{{ role_path }}/files/apt-sources/raspbian-main.list"
    dest: /etc/apt/sources.list
  when: common__host_type == "rpi"
  register: common__sources_rpi_main

- name: "Install Raspberry Pi sources - archive"
  copy:
    src: "{{ role_path }}/files/apt-sources/raspbian-archive.list"
    dest: /etc/apt/sources.list.d/raspi.list
  when: common__host_type == "rpi"
  register: common__sources_rpi_archive

- name: "Install stock Debian sources - main"
  copy:
    src: "{{ role_path }}/files/apt-sources/stock-debian.list"
    dest: /etc/apt/sources.list
  when: common__host_type == "stock"
  register: common__sources_stock

- name: "Run apt update if any sources changed"
  apt:
    update_cache: yes
  when: common__sources_rpi_main.changed or common__sources_rpi_archive.changed or common__sources_stock.changed

# Sane environment

- name: "Install system fundamentals"
  apt: name=ntp

- name: "UTC system clock"
  timezone: name=Etc/UTC
  register: common__timezone

- name: "Restart cron when timezone changed"
  service: name=cron state=restarted
  when: common__timezone.changed

# Adminning

- name: Sysadmin basics
  apt:
    name:
    - ssh
    - rsync
    - emacs
    - screen
    - curl
    - locate
    - socat
    - lsof
    - dnsutils # dig, nslookup

# FIXME: include is deprecated; use import_tasks when upgrade from
# ansible 2.2 to 2.4
- include: unattended-upgrades.yml

- name: SSH configuration
  copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
  notify: reload sshd config

# 244 is the sum of:
#
#   0x4 - enable control of keyboard (SAK, unraw)
#  0x10 - enable sync command
#  0x20 - enable remount read-only
#  0x40 - enable signalling of processes (term, kill, oom-kill)
#  0x80 - allow reboot/poweroff
#
# https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html

- name: "Magic SysRq key config"
  ansible.posix.sysctl:
    name: kernel.sysrq
    # Has to be decimal or ansible will always think it has changed,
    # since sysctl reports it back as decimal even if you set it using
    # hexadecimal.
    value: "244"
    sysctl_set: true
