---

# Fundamental setup

- name: Root ssh folder
  file:
    state: directory
    path: "/root/.ssh"
    owner: root
    group: root
    mode: 0700

- name: Trusted Ansible key
  copy:
    src: "{{ role_path }}/files/id_ansible_appux.pub"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0644

# Sane environment

- name: "Install system fundamentals"
  apt: name=ntp

- name: "UTC system clock"
  timezone: name=Etc/UTC
  register: common__timezone

- name: "Restart cron when timezone changed"
  service: name=cron state=restarted
  when: common__timezone.changed

# Adminning

- name: Sysadmin basics
  apt:
    name:
    - ssh
    - rsync
    - emacs
    - screen
    - curl
    - locate
    - socat
    - lsof
    - dnsutils # dig, nslookup

# FIXME: include is deprecated; use import_tasks when upgrade from
# ansible 2.2 to 2.4
- include: unattended-upgrades.yml

- name: SSH configuration
  copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
  notify: reload sshd config
