---
- name: "Install unattended-upgrades"
  apt: name=unattended-upgrades
- copy:
    src: "{{ role_path }}/files/apt.conf.d/50unattended-upgrades"
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
- copy:
    src: "{{ role_path }}/files/apt.conf.d/20auto-upgrades"
    dest: /etc/apt/apt.conf.d/20auto-upgrades

