---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted (for dyndns data)"
  shell: mountpoint /srv/commdata
  changed_when: False

# ----

- name: "Directory for dyndns data"
  file:
    state: directory
    path: /srv/commdata/dyndns

- name: "Dyndns data"
  copy:
    content: |
      DYNDNS_BASE_DOMAIN={{ dyndns__base_domain|quote }}
      DYNDNS_RECORD={{ dyndns__record|quote }}
      DYNDNS_TTL_S=180 # should be shorter than cron update interval
    dest: /srv/commdata/dyndns/config

- name: Directory for dyndns scripts
  file:
    state: directory
    path: /opt/commapps/dyndns

- name: Install dyndns updater script
  copy:
    src: "{{ role_path }}/files/dns-update.sh"
    dest: /opt/commapps/dyndns/dns-update.sh
    mode: preserve

- name: "Create log file writeable by dyndns user"
  file:
    path: /var/log/dyndns-appux.log
    # This is required in order to ensure the file is *present* and
    # also gets correct mode/owner, but doesn't get touched if already
    # present. Thanks to https://github.com/ansible/ansible/issues/7490
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Install dyndns cron job
  copy:
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
      */4 * * * * root /opt/commapps/dyndns/dns-update.sh >> /var/log/dyndns-appux.log 2>&1
    dest: /etc/cron.d/dyndns-appux-update

- name: Rotate logs
  copy:
    content: |
      /var/log/dyndns-appux.log {
        weekly
        rotate 5
        missingok
        create root root
      }
    dest: /etc/logrotate.d/appux-dyndns
