---
- name: "Install apt-src"
  apt: name=apt-src

- name: "Make build dir for tarsnap"
  file:
    state: directory
    path: /opt/commapps/compile

- name: "Check if already installed"
  shell: "apt-src version tarsnap"
  register: tarsnap__apt_src_version
  failed_when: False
  changed_when: False
  check_mode: no

- name: "Build from source and install"
  when: tarsnap__apt_src_version.rc != 0
  shell: |
    apt-src update
    # - "Installs" source package into dir, or upgrades it as needed
    # - Builds a deb package out of it
    # - Install the deb pkg
    apt-src --location /opt/commapps/compile --build --keep-built \
      --installdebs install tarsnap
