supervisor__hosts:
  - name: toster
  - name: murphy

# Passphrase to decrypt the full keys below.
supervisor__tarsnap_key_pass: "{{ vault_supervisor__tarsnap_key_pass }}"

# Full-powered Tarsnap keys for every host. See tarsnap role README.md
# for details.
#
# This indirection allows the data to stay out of lists that we might
# iterate over in the playbook, where the keys could inadvertantly be
# logged to stderr.  By keeping just the keys in this dict, we reduce
# the number of places where we have to use `no_log: true` (and where
# we might forget to!)
supervisor__tarsnap_full_keys:
  # Rotated 2020-12-20
  toster: "{{ vault_supervisor__tarsnap_full_enc_key_toster }}"
  # Rotated 2020-12-20
  murphy: "{{ vault_supervisor__tarsnap_full_enc_key_murphy }}"
