---
- name: "Install Tarsnap deb packaging key"
  apt_key:
    url: https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc
    state: present
    id: "8E64CEEC8767B49710E308F770BD6C50E82A9D99"

- name: "Use Tarsnap package repository"
  copy:
    content: |
      # Ansible: remote-backup role
      deb http://pkg.tarsnap.com/deb/{{ debversion }} ./
    dest: /etc/apt/sources.list.d/tarsnap.list

- name: "Install tarsnap"
  apt: name=tarsnap
