---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- name: "Create dyndns updater user with few permissions"
  user:
    name: dyndns_upd
    system: yes

- name: "Directory for dyndns data"
  file:
    state: directory
    path: /srv/commdata/dyndns

- name: "Directory for dyndns secrets"
  file:
    state: directory
    path: /srv/commdata/dyndns/secrets
    owner: dyndns_upd
    group: dyndns_upd
    mode: u=rx,g=,o=

- name: Write afraid.org secret token
  copy:
    content: "{{ dyndns_afraidorg_token }}"
    dest: /srv/commdata/dyndns/secrets/afraid.org-token-home
    owner: dyndns_upd
    group: dyndns_upd
    mode: u=r,g=,o=
  no_log: true

# ----

- name: Directory for dyndns scripts
  file:
    state: directory
    path: /opt/commapps/dyndns

- name: Install dyndns updater script
  copy:
    src: "{{ role_path }}/files/dns-update.sh"
    dest: /opt/commapps/dyndns/dns-update.sh
    mode: preserve

- name: "Create log file writeable by dyndns user"
  file:
    path: /var/log/dyndns-afraid.org-home.log
    owner: dyndns_upd
    group: dyndns_upd
    # This is required in order to ensure the file is *present* and
    # also gets correct mode/owner, but doesn't get touched if already
    # present. Thanks to https://github.com/ansible/ansible/issues/7490
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Install dyndns cron job
  copy:
    content: |
      SHELL=/bin/bash
      PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
      # Randomized [0..59] sleep to reduce impact on afraid.org
      DYNDNS_SLEEP=20
      */3 * * * * dyndns_upd /opt/commapps/dyndns/dns-update.sh >> /var/log/dyndns-afraid.org-home.log 2>&1
    dest: /etc/cron.d/dyndns-afraid-org-update

- name: Rotate logs
  copy:
    content: |
      /var/log/dyndns-afraid.org-home.log {
        weekly
        rotate 5
        missingok
        create dyndns_upd dyndns_upd
      }
    dest: /etc/logrotate.d/appux-dyndns
