---
# Double-check. See redundant task in commdata for more info.
# TODO: Rotate secrets now that this check is in place
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

- name: Directory for dyndns secrets
  file:
    state: directory
    path: /srv/commdata/dyndns/secrets
    owner: root
    group: root
    mode: 0600

- name: Write afraid.org secret token
  copy:
    content: "{{ dyndns_afraidorg_token }}"
    dest: /srv/commdata/dyndns/secrets/afraid.org-token-home
    owner: root
    group: root
    mode: 0600
  no_log: true

# ----

- name: Directory for dyndns scripts
  file:
    state: directory
    path: /opt/commapps/dyndns
    owner: root
    group: root
    mode: 0755

- name: Install dyndns updater script
  copy:
    src: "{{ role_path }}/files/dns-update.sh"
    dest: /opt/commapps/dyndns/dns-update.sh
    owner: root
    group: root
    mode: 0755

# TODO: Create dyndns user and run with lowered permissions

- name: Install dyndns cron job
  copy:
    content: |
      PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
      */3 * * * * root /opt/commapps/dyndns/dns-update.sh >> /var/log/dyndns-afraid.org-home.log 2>&1
    dest: /etc/cron.d/dyndns-afraid-org-update

- name: Rotate logs
  copy:
    content: |
      /var/log/dyndns-afraid.org-home.log {
        weekly
        rotate 5
        missingok
      }
    dest: /etc/logrotate.d/appux-dyndns
