---

- name: Directory for dyndns secrets
  file:
    state: directory
    path: /opt/commdata/dyndns/secrets
    owner: root
    group: root
    mode: 0600

- name: Write afraid.org secret token
  copy:
    content: "{{ dyndns_afraidorg_token }}"
    dest: /opt/commdata/dyndns/secrets/afraid.org-token-home
    owner: root
    group: root
    mode: 0600

- name: Install dyndns updater script
  copy:
    src: "{{ role_path }}/files/dns-update.sh"
    dest: /opt/commdata/dyndns/dns-update.sh
    owner: root
    group: root
    mode: 0755

- name: Install dyndns cron job
  copy:
    src: "{{ role_path }}/files/dns-update.cron"
    dest: /etc/cron.d/dyndns-afraid-org-update
    owner: root
    group: root
    mode: 0644
