---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- name: "Create dyndns updater user with few permissions"
  user:
    name: dyndns_upd
    system: yes

- name: Directory for dyndns secrets
  file:
    state: directory
    path: /srv/commdata/dyndns/secrets
    owner: dyndns_upd
    group: dyndns_upd
    mode: u=r

- name: Write afraid.org secret token
  copy:
    content: "{{ dyndns_afraidorg_token }}"
    dest: /srv/commdata/dyndns/secrets/afraid.org-token-home
    owner: dyndns_upd
    group: dyndns_upd
    mode: u=r
  no_log: true

# ----

- name: Directory for dyndns scripts
  file:
    state: directory
    path: /opt/commapps/dyndns
    owner: root
    group: root
    mode: 0755

- name: Install dyndns updater script
  copy:
    src: "{{ role_path }}/files/dns-update.sh"
    dest: /opt/commapps/dyndns/dns-update.sh
    owner: root
    group: root
    mode: 0755

- name: Install dyndns cron job
  copy:
    content: |
      PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
      */3 * * * * dyndns_upd /opt/commapps/dyndns/dns-update.sh >> /var/log/dyndns-afraid.org-home.log 2>&1
    dest: /etc/cron.d/dyndns-afraid-org-update

- name: Rotate logs
  copy:
    content: |
      /var/log/dyndns-afraid.org-home.log {
        weekly
        rotate 5
        missingok
        create dyndns_upd dyndns_upd
      }
    dest: /etc/logrotate.d/appux-dyndns

# TODO delete (one-off)
- name: "Set log file to correct owner, if present"
  file:
    path: "/var/log/dyndns-afraid.org-home.log"
    state: file
    owner: dyndns_upd
    group: dyndns_upd
