---
# All hosts get the common setup
- hosts: all
  remote_user: root
  roles:
    - common
# murphy is a Raspberry Pi, planned to be the supervisor
- hosts: murphy.internal
  remote_user: root
  roles:
    - dyndns
# toster is a laptop
- hosts: toster.internal
  remote_user: root
  roles:
    - laptop
    - role: sandstorm
      sandstorm_base_domain: sandstorm.appux.com
      sandstorm_old_domain: sandy.parsni.ps
    - jabber
