---
# Double-check. See redundant task in commdata for more info.
# TODO: Rotate secrets now that this check is in place
- name: "Confirm that commdata is mounted"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- include: terminate-tls.yml # TODO: rename to proxy-config.yml to not be confused with role
- include: sandstorm.yml

- name: "Sites hosted in grains"
  include_tasks: grain_site.yml
  loop:
    - purpose: "Spelunk's WebDAV integration test server"
      domain: spelunk-webdav-testing.spidersge.org
