---

# TODO Tasks for creating commdata
# TODO Tasks for ensuring nginx doesn't start until commdata partition unlocked

#== ACME wildcard cert renewal ==#

- name: Install certbot
  apt: name=certbot

- name: Certbot secrets directory
  file:
    path: "{{ commdata_dir }}/secrets/certbot"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Certbot config directory
  file:
    path: "{{ commdata_dir }}/etc-letsencrypt" # Replaces /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Certbot configuration"
  copy:
    src: "{{ role_path }}/files/certbot/certbot.ini"
    dest: "{{ commdata_dir }}/etc-letsencrypt/certbot.ini"

- name: NFSN API key
  copy:
    content: "{{ sandstorm__nfsn_api_key }}"
    dest: "{{ commdata_dir }}/secrets/certbot/nfsn-api-key"
    owner: root
    group: root
    mode: 0600
  no_log: true

- name: Certbot management files
  file:
    state: directory
    path: /opt/commapps/certbot

- name: Certbot cert scipts
  synchronize:
    src: "{{ role_path }}/files/certbot/scripts/"
    dest: /opt/commapps/certbot/scripts/
  register: certbot__scripts

- name: Initial certbot run so nginx can start
  command: /opt/commapps/certbot/scripts/renew-certs.sh
  when: certbot__scripts.changed

- name: Schedule daily renewal check
  copy:
    src: "{{ role_path }}/files/certbot/certbot.cron"
    dest: /etc/cron.d/commapps-certbot


#==#

- name: Sandstorm nginx configuration
  template:
    src: nginx-sites/sandstorm.conf.j2
    dest: /etc/nginx/sites-available/sandstorm.conf
  notify: nginx reload config
- name: Enable nginx configuration
  file:
    src: /etc/nginx/sites-available/sandstorm.conf
    dest: /etc/nginx/sites-enabled/sandstorm.conf
    state: link
  notify: nginx reload config
