---
- name: "certs config update"
  command: /opt/commapps/certbot/scripts/renew-certs.sh

- name: "nginx reload config"
  service:
    name: nginx
    state: reloaded
    enabled: yes

# Note that reload is not implemented for this service, so config
# changes should target this handler too.
- name: "dendrite change"
  service:
    name: dendrite
    state: restarted

- name: "regui config change"
  service:
    name: matrix-registration
    state: restarted
