---
- name: Install nginx
  apt: name=nginx

- name: Directory for nginx ssl params
  file:
    path: "/etc/nginx/ssl"
    state: directory

- name: Predefined Diffie-Hellman group
  copy:
    src: "{{ role_path }}/files/ffdhe4096.pem"
    dest: "/etc/nginx/ssl/ffdhe4096.pem"
  notify: nginx reload config

- name: "nginx global config"
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify: nginx reload config
