---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted (for matrix data)"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- name: "Dir for matrix files"
  file:
    path: "{{ matrix__cfg.data_dir }}"
    state: directory

- name: "User and home dir for dendrite"
  user:
    name: "{{ matrix__cfg.user }}"
    system: yes
    home: "{{ matrix__cfg.data_dir }}/dendrite"
    shell: /bin/bash

- name: "PostgreSQL for backing store"
  apt:
    name:
      - postgresql
      - python3-psycopg2 # Python adapter, required for postgresql ansible modules

- name: "A place for dendrite postgres data"
  file:
    state: directory
    path: "{{ matrix__cfg.data_dir }}/dendrite/postgres"
    owner: postgres
    group: postgres

# NB: This relies on a hacky Before+RequiredBy declaration in
# commdata-fs.service that ensures postgresql won't start until after
# the commdata filesystem is mounted.
- name: "Allow postgres to store dendrite tables in commdata"
  community.postgresql.postgresql_tablespace:
    tablespace: "{{ matrix__cfg.pg.tablespace }}"
    location: "{{ matrix__cfg.data_dir }}/dendrite/postgres"
  become: true
  become_user: postgres

- name: "Dendrite DB, stored in commdata"
  community.postgresql.postgresql_db:
    name: "{{ matrix__cfg.pg.db }}"
    tablespace: "{{ matrix__cfg.pg.tablespace }}"
  become: true
  become_user: postgres

- name: "Dendrite user account in postgres"
  community.postgresql.postgresql_user:
    name: "{{ matrix__cfg.pg.user }}"
    password: "{{ matrix__cfg.pg.password }}"
    db: "{{ matrix__cfg.pg.db }}"
  no_log: true # secrets
  become: true
  become_user: postgres


#== Building dendrite

- name: "Script to build from source"
  template:
    src: "{{ role_path }}/templates/build-dendrite.sh.j2"
    dest: "{{ matrix__cfg.data_dir }}/build-dendrite.sh"
    mode: a=rx

- name: "Build dendrite"
  command:
    creates: "{{ matrix__cfg.data_dir }}/dendrite/bin/dendrite-{{ matrix__cfg.dendrite_version }}/dendrite-monolith-server"
    cmd: "{{ matrix__cfg.data_dir }}/build-dendrite.sh"
  become: yes
  become_user: "{{ matrix__cfg.user }}"
  environment:
    GOLANG_VER: "{{ matrix__cfg.golang_version }}"
    GOLANG_SHA256: "{{ matrix__cfg.golang_archive_sha256 }}"
    DENDRITE_REPO_URL: "{{ matrix__cfg.dendrite_repo_url }}"
    DENDRITE_VER: "{{ matrix__cfg.dendrite_version }}"
    DENDRITE_COMMIT_SHA1: "{{ matrix__cfg.dendrite_commit_sha1 }}"

- name: "Symlink to current version for ease of reference"
  file:
    state: link
    path: "{{ matrix__cfg.data_dir }}/dendrite/bin/current"
    src: "dendrite-{{ matrix__cfg.dendrite_version }}"
    follow: false # set ownership on link, not dest
    owner: "{{ matrix__cfg.user }}"
    group: "{{ matrix__cfg.user }}"
  notify: "dendrite change"

#== TLS termination via nginx

- name: "Certificate config"
  copy:
    content: "{{ item.config | to_nice_json }}"
    dest: "/opt/commapps/certbot/domains.d/{{ item.filename }}"
  loop: "{{ matrix__cfg.certificates}}"
  notify: "certs config update"

- name: "Install nginx proxy"
  copy:
    content: |
      # Configuration for {{ matrix__cfg.domain_host }} reverse proxy
      server {
        listen 443 ssl;
        server_name {{ matrix__cfg.domain_host }};

        ssl_certificate /srv/commdata/etc-letsencrypt/live/{{ matrix__cfg.domain_host }}/fullchain.pem;
        ssl_certificate_key /srv/commdata/etc-letsencrypt/live/{{ matrix__cfg.domain_host }}/privkey.pem;

        # If someone opens the subdomain in their browser, send them
        # to a useful page.
        location ~ ^/$ {
          return 302 {{ matrix__cfg.root_url_redirect }};
        }

        # Registration UI is separate application. Only expose routes
        # that need to be public; admin API will only be callable from
        # on-host.
        location ~ ^/regui/(static|register) {
          proxy_pass http://localhost:{{ matrix__cfg.regui.listen_port }};
          proxy_read_timeout 30;
        }

        # Everything else goes to Dendrite.
        location ~ ^/.+ {
          proxy_pass http://127.0.0.1:{{ matrix__cfg.dendrite_listen_port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_read_timeout 600;
        }

        # Allow file uploads. Dendrite has its own config on the Media
        # API side, so this can be somewhat permissive.
        client_max_body_size 15m;
      }
    dest: "/etc/nginx/sites-available/{{ matrix__cfg.domain_host }}.conf"
  notify: "nginx reload config"

- name: "Enable nginx proxy"
  file:
    src: "/etc/nginx/sites-available/{{ matrix__cfg.domain_host }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ matrix__cfg.domain_host }}.conf"
    state: link
  notify: "nginx reload config"

#== Configuration

- name: "Directory for dendrite logs"
  file:
    path: "{{ matrix__cfg.data_dir }}/dendrite/logs"
    state: directory
    owner: "{{ matrix__cfg.user }}"
    group: "{{ matrix__cfg.user }}"
    # Logs could contain user info
    mode: u=rwx,g=,o=

- name: "Signing key"
  copy:
    content: "{{ matrix__cfg.signing_key }}"
    dest: "{{ matrix__cfg.data_dir }}/dendrite/matrix_key.pem"
    owner: "{{ matrix__cfg.user }}"
    group: "{{ matrix__cfg.user }}"
    mode: u=r,g=,o=
  no_log: true
  notify: "dendrite change"

- name: "Dendrite config file"
  template:
    src: "{{ role_path }}/templates/dendrite.yaml.j2"
    dest: "{{ matrix__cfg.data_dir }}/dendrite/dendrite.yaml"
    owner: "{{ matrix__cfg.user }}"
    group: "{{ matrix__cfg.user }}"
    mode: u=r,g=,o=
  no_log: true # contains secrets
  notify: "dendrite change"

- name: "Dendrite launcher"
  copy:
    content: |
      #!/bin/bash
      set -eu -o pipefail
      {{ matrix__cfg.data_dir|quote }}/dendrite/bin/current/dendrite-monolith-server \
          --config {{ matrix__cfg.data_dir|quote }}/dendrite/dendrite.yaml \
          --http-bind-address localhost:{{ matrix__cfg.dendrite_listen_port|quote }} \
          >> {{ matrix__cfg.data_dir|quote }}/dendrite/logs/stdout.log \
          2>> {{ matrix__cfg.data_dir|quote }}/dendrite/logs/stderr.log
    dest: "{{ matrix__cfg.data_dir }}/dendrite/run.sh"
    owner: "{{ matrix__cfg.user }}"
    group: "{{ matrix__cfg.user }}"
    mode: a+x
  notify: "dendrite change"

# Only needed for stderr/stdout files; dendrite rotates its own logs.
# stderr.log actually seems to just be a terser version of what's in
# Monolith.log, but keeping it anyway for now.
- name: "Log rotation"
  copy:
    content: |
      {{ matrix__cfg.data_dir|quote }}/dendrite/logs/stdout.log {{ matrix__cfg.data_dir|quote }}/dendrite/logs/stderr.log {
          daily
          rotate 10
          missingok
          create 600 {{ matrix__cfg.user }} {{ matrix__cfg.user }}
      }
    dest: "/etc/logrotate.d/{{ matrix__cfg.service_name }}-launcher"

- name: "Dendrite systemd service unit file"
  copy:
    content: |
      [Unit]
      Description=Dendrite Matrix server

      # nginx not listed, since it's not a hard requirement for the
      # process, just the service being reachable.
      Requires=commdata-fs.service
      Requires=postgresql.service
      After=commdata-fs.service
      After=postgresql.service

      # If it auto-restarts this many times in this many seconds, stop
      # auto-restarting.
      StartLimitBurst=3
      StartLimitIntervalSec=30

      [Service]
      Type=simple
      ExecStart={{ matrix__cfg.data_dir }}/dendrite/run.sh
      User={{ matrix__cfg.user }}
      Group={{ matrix__cfg.user }}

      Restart=on-failure
      RestartSec=5s

      # Dendrite needs to talk to lots of homeservers
      LimitNOFILE=8K
      # Dendrite is experimental and sometimes leaks memory. If
      # there's an OOM situation, it's probably Dendrite, so prefer to
      # kill it.
      OOMScoreAdjust=500

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/{{ matrix__cfg.service_name }}.service"
  register: matrix__dendrite_service_file

- name: "Reload systemd config if dendrite unit file changed"
  command: systemctl daemon-reload
  when: matrix__dendrite_service_file.changed

- name: "Enable dendrite service"
  service:
    name: "{{ matrix__cfg.service_name }}"
    enabled: yes
    state: started

#== Matrix registration frontend

- name: "User and home dir for matreg"
  user:
    name: "{{ matrix__cfg.regui.user }}"
    system: yes
    home: "{{ matrix__cfg.data_dir }}/regui"
    shell: /bin/bash

- name: "Deps for matrix-registration"
  apt:
    name:
      # Virtualenv
      - python3
      - python3-pip
      - python3-virtualenv
      # Administration
      - sqlite3

- name: "Setup by matreg user"
  become: yes
  become_user: "{{ matrix__cfg.regui.user }}"
  block:
    # Maintain a different virtualenv for each Python version so that when
    # the operating system upgrades Python and *uninstalls the old default
    # Python* that the venv pointed to, the next Ansible run will recreate
    # the venv with the new Python version.

    - name: "Discover Python version"
      shell: |
        python3 -c "import platform; print(platform.python_version(), end='')"
      failed_when: False
      changed_when: False
      register: matreg__pyver
      check_mode: no # Run in normal mode, since it registers a variable

    - name: "Install matrix-registration in virtualenv"
      pip:
        name:
          # Tagged v0.9.1 but author forgot to bump the version; this is
          # probably the one labeled 0.9.1.post1 on PyPI
          - "git+https://github.com/ZerataX/matrix-registration@ac0291749c869e258fa7d3fbdd84fb25f1fa9b50#egg=matrix-registration==0.9.0"
        virtualenv: "{{ matrix__cfg.data_dir }}/regui/venv_py{{ matreg__pyver.stdout}}"
        virtualenv_python: python3

    - name: "Symlink for virtualenv matching current Python"
      file:
        state: link
        src: "{{ matrix__cfg.data_dir }}/regui/venv_py{{ matreg__pyver.stdout }}"
        dest: "{{ matrix__cfg.data_dir }}/regui/venv"

    - name: "Directory for regui logs"
      file:
        path: "{{ matrix__cfg.data_dir }}/regui/logs"
        state: directory
        # Logs could contain user info
        mode: u=rwx,g=,o=

    - name: "Configuration for registration app"
      template:
        src: "{{ role_path }}/templates/matrix-registration.yaml.j2"
        dest: "{{ matrix__cfg.data_dir }}/regui/config.yaml"
      no_log: true # secrets

    - name: "Registration app launcher"
      copy:
        content: |
          #!/bin/bash
          set -eu -o pipefail
          {{ matrix__cfg.data_dir|quote }}/regui/venv/bin/matrix-registration \
            --config-path {{ matrix__cfg.data_dir|quote }}/regui/config.yaml \
            serve \
            >> {{ matrix__cfg.data_dir|quote }}/regui/logs/stdout.log \
            2>> {{ matrix__cfg.data_dir|quote }}/regui/logs/stderr.log
        dest: "{{ matrix__cfg.data_dir }}/regui/run.sh"
        mode: a+x
      notify: "regui config change"

    - name: "Registration app admin script"
      copy:
        content: |
          #!/bin/bash
          # Make calls to admin API via curl
          set -eu -o pipefail

          if [[ "$#" -lt 1 ]]; then
            echo "Usage: admin.sh /api/... [optional curl args...]"
            exit 1
          fi

          api_path="$1" # e.g. "version"
          shift

          if [[ ! "$api_path" =~ ^/api/.* ]]; then
            echo "Path must start with /api/"
            exit 1
          fi

          curl -sS \
            -H "Authorization: SharedSecret {{ matrix__cfg.regui.admin_password }}" \
            "http://localhost:{{ matrix__cfg.regui.listen_port }}${api_path}" \
            "$@"
        dest: "{{ matrix__cfg.data_dir }}/regui/admin.sh"
        mode: u=rwx,g=,o=
      no_log: true # secrets


- name: "Log rotation"
  copy:
    content: |
      {{ matrix__cfg.data_dir|quote }}/regui/logs/stdout.log {{ matrix__cfg.data_dir|quote }}/regui/logs/stderr.log {
          daily
          rotate 20
          missingok
          create 600 {{ matrix__cfg.regui.user }} {{ matrix__cfg.regui.user }}
      }
    dest: "/etc/logrotate.d/{{ matrix__cfg.regui.service_name }}-launcher"

- name: "Registration systemd service unit file"
  copy:
    content: |
      [Unit]
      Description=Matrix registration service

      # nginx not listed, since it's not a hard requirement for the
      # process, just the service being reachable.
      Requires=commdata-fs.service
      After=commdata-fs.service

      # If it auto-restarts this many times in this many seconds, stop
      # auto-restarting.
      StartLimitBurst=3
      StartLimitIntervalSec=30

      [Service]
      Type=simple
      ExecStart={{ matrix__cfg.data_dir }}/regui/run.sh
      User={{ matrix__cfg.regui.user }}
      Group={{ matrix__cfg.regui.user }}

      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/{{ matrix__cfg.regui.service_name }}.service"
  register: matrix__regui_service_file

- name: "Reload systemd config if registration unit file changed"
  command: systemctl daemon-reload
  when: matrix__regui_service_file.changed

- name: "Enable registration service"
  service:
    name: "{{ matrix__cfg.regui.service_name }}"
    enabled: yes
    state: started
