---
# Double-check. See redundant task in commdata for more info.
- name: "Confirm that commdata is mounted (for matrix data)"
  shell: mountpoint /srv/commdata
  changed_when: False

# Mechanism for vars/vault separation for role vars
- include_vars: "{{ role_path }}/vars/vault.yml"

# ----

- name: "Dir for matrix files"
  file:
    path: "/srv/commdata/matrix"
    state: directory

- name: "User and home dir for dendrite"
  user:
    name: dendrite
    system: yes
    home: /srv/commdata/matrix/dendrite
    shell: /bin/bash

- name: "PostgreSQL for backing store"
  apt:
    name:
      - postgresql
      - python3-psycopg2 # Python adapter, required for postgresql ansible modules

- name: "A place for dendrite postgres data"
  file:
    state: directory
    path: "/srv/commdata/matrix/dendrite/postgres"
    owner: postgres
    group: postgres

# NB: This relies on a hacky Before+RequiredBy declaration in
# commdata-fs.service that ensures postgresql won't start until after
# the commdata filesystem is mounted.
- name: "Allow postgres to store dendrite tables in commdata"
  community.postgresql.postgresql_tablespace:
    tablespace: commdata_dendrite
    location: "/srv/commdata/matrix/dendrite/postgres"
  become: true
  become_user: postgres

- name: "Dendrite DB, stored in commdata"
  community.postgresql.postgresql_db:
    name: dendrite
    tablespace: commdata_dendrite
  become: true
  become_user: postgres

- name: "Dendrite user account in postgres"
  community.postgresql.postgresql_user:
    name: dendrite
    password: "{{ matrix__postgres_password }}"
    db: dendrite
  no_log: true # secrets
  become: true
  become_user: postgres


#== Building dendrite

- name: "Dir for matrix binaries and builds"
  file:
    path: "/opt/commapps/matrix"
    state: directory

- name: "Dir for building"
  file:
    path: "/opt/commapps/matrix/dendrite"
    state: directory
    owner: dendrite
    group: dendrite

- name: "Script to build from source"
  copy:
    src: "{{ role_path }}/files/build-dendrite.sh"
    dest: "/opt/commapps/matrix/build-dendrite.sh"
    mode: a=rx

- name: "Build dendrite"
  command:
    creates: "/srv/commdata/matrix/dendrite/bin/dendrite-{{ matrix__dendrite_version }}/dendrite-monolith-server"
    cmd: /opt/commapps/matrix/build-dendrite.sh
  become: yes
  become_user: dendrite
  environment:
    GOLANG_VER: "{{ matrix__golang_version }}"
    GOLANG_SHA256: "{{ matrix__golang_archive_sha256 }}"
    DENDRITE_REPO_URL: "{{ matrix__dendrite_repo_url }}"
    DENDRITE_VER: "{{ matrix__dendrite_version }}"
    DENDRITE_COMMIT_SHA1: "{{ matrix__dendrite_commit_sha1 }}"

- name: "Symlink to current version for ease of reference"
  file:
    state: link
    path: /srv/commdata/matrix/dendrite/bin/current
    src: "dendrite-{{ matrix__dendrite_version }}"
    follow: false # set ownership on link, not dest
    owner: dendrite
    group: dendrite
  notify: "dendrite change"

#== TLS termination via nginx

- name: "Certificate config"
  copy:
    content: "{{ item.config | to_nice_json }}"
    dest: "/opt/commapps/certbot/domains.d/{{ item.filename }}"
  loop:
    - filename: matrix-sub.json
      config:
        sub: matrix
        base: appux.com
        wild: false
  notify: "certs config update"

- name: "Install nginx proxy"
  copy:
    content: |
      # Configuration for matrix.appux.com reverse proxy
      server {
        listen 443 ssl;
        server_name matrix.appux.com;

        ssl_certificate /srv/commdata/etc-letsencrypt/live/matrix.appux.com/fullchain.pem;
        ssl_certificate_key /srv/commdata/etc-letsencrypt/live/matrix.appux.com/privkey.pem;

        # If someone opens the subdomain in their browser, send them
        # to a useful page.
        location ~ ^/$ {
          return 302 https://www.appux.com/matrix.html;
        }

        # Registration UI is separate application. Only expose routes
        # that need to be public; admin API will only be callable from
        # on-host.
        location ~ ^/regui/(static|register) {
          proxy_pass http://localhost:{{ matrix__regui_listen_port }};
          proxy_read_timeout 30;
        }

        # Everything else goes to Dendrite.
        location ~ ^/.+ {
          proxy_pass http://127.0.0.1:{{ matrix__dendrite_listen_port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_read_timeout 600;
        }

        # Allow file uploads. Dendrite has its own config on the Media
        # API side, so this can be somewhat permissive.
        client_max_body_size 15m;
      }
    dest: "/etc/nginx/sites-available/matrix.appux.com.conf"
  notify: "nginx reload config"

- name: "Enable nginx proxy"
  file:
    src: "/etc/nginx/sites-available/matrix.appux.com.conf"
    dest: "/etc/nginx/sites-enabled/matrix.appux.com.conf"
    state: link
  notify: "nginx reload config"

#== Configuration

- name: "Directory for dendrite logs"
  file:
    path: /srv/commdata/matrix/dendrite/logs
    state: directory
    owner: dendrite
    group: dendrite
    # Logs could contain user info
    mode: u=rwx,g=,o=

- name: "Signing key"
  copy:
    content: "{{ matrix__signing_key }}"
    dest: /srv/commdata/matrix/dendrite/matrix_key.pem
    owner: dendrite
    group: dendrite
    mode: u=r,g=,o=
  no_log: true
  notify: "dendrite change"

- name: "Dendrite config file"
  template:
    src: "{{ role_path }}/templates/dendrite.yaml.j2"
    dest: /srv/commdata/matrix/dendrite/dendrite.yaml
    owner: dendrite
    group: dendrite
    mode: u=r,g=,o=
  no_log: true # contains secrets
  notify: "dendrite change"

- name: "Dendrite launcher"
  copy:
    content: |
      #!/bin/bash
      set -eu -o pipefail
      /srv/commdata/matrix/dendrite/bin/current/dendrite-monolith-server \
          --config /srv/commdata/matrix/dendrite/dendrite.yaml \
          --http-bind-address localhost:{{ matrix__dendrite_listen_port }} \
          >> /srv/commdata/matrix/dendrite/logs/stdout.log \
          2>> /srv/commdata/matrix/dendrite/logs/stderr.log
    dest: /srv/commdata/matrix/dendrite/run.sh
    owner: dendrite
    group: dendrite
    mode: a+x
  notify: "dendrite change"

# Only needed for stderr/stdout files; dendrite rotates its own logs.
# stderr.log actually seems to just be a terser version of what's in
# Monolith.log, but keeping it anyway for now.
- name: "Log rotation"
  copy:
    content: |
      /srv/commdata/matrix/dendrite/logs/stdout.log /srv/commdata/matrix/dendrite/logs/stderr.log {
          daily
          rotate 10
          missingok
          create 600 dendrite dendrite
      }
    dest: /etc/logrotate.d/dendrite-launcher

- name: "Dendrite systemd service unit file"
  copy:
    content: |
      [Unit]
      Description=Dendrite Matrix server

      # nginx not listed, since it's not a hard requirement for the
      # process, just the service being reachable.
      Requires=commdata-fs.service
      Requires=postgresql.service
      After=commdata-fs.service
      After=postgresql.service

      # If it auto-restarts this many times in this many seconds, stop
      # auto-restarting.
      StartLimitBurst=3
      StartLimitIntervalSec=30

      [Service]
      Type=simple
      ExecStart=/srv/commdata/matrix/dendrite/run.sh
      User=dendrite
      Group=dendrite

      Restart=on-failure
      RestartSec=5s

      # Dendrite needs to talk to lots of homeservers
      LimitNOFILE=8K
      # Dendrite is experimental and sometimes leaks memory. If
      # there's an OOM situation, it's probably Dendrite, so prefer to
      # kill it.
      OOMScoreAdjust=500

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/dendrite.service
  register: matrix__dendrite_service_file

- name: "Reload systemd config if dendrite unit file changed"
  command: systemctl daemon-reload
  when: matrix__dendrite_service_file.changed

- name: "Enable dendrite service"
  service:
    name: dendrite
    enabled: yes
    state: started

#== Matrix registration frontend

- name: "User and home dir for matreg"
  user:
    name: matreg
    system: yes
    home: /srv/commdata/matrix/regui
    shell: /bin/bash

- name: "Deps for matrix-registration virtualenv"
  apt:
    name:
      - python3
      - python3-pip
      - python3-virtualenv

- name: "Setup by matreg user"
  become: yes
  become_user: matreg
  block:
    # Maintain a different virtualenv for each Python version so that when
    # the operating system upgrades Python and *uninstalls the old default
    # Python* that the venv pointed to, the next Ansible run will recreate
    # the venv with the new Python version.

    - name: "Discover Python version"
      shell: |
        python3 -c "import platform; print(platform.python_version(), end='')"
      failed_when: False
      changed_when: False
      register: matreg__pyver
      check_mode: no # Run in normal mode, since it registers a variable

    - name: "Install matrix-registration in virtualenv"
      pip:
        name:
          # Tagged v0.9.1 but author forgot to bump the version; this is
          # probably the one labeled 0.9.1.post1 on PyPI
          - "git+https://github.com/ZerataX/matrix-registration@ac0291749c869e258fa7d3fbdd84fb25f1fa9b50#egg=matrix-registration==0.9.0"
        virtualenv: "/srv/commdata/matrix/regui/venv_py{{ matreg__pyver.stdout}}"
        virtualenv_python: python3

    - name: "Symlink for virtualenv matching current Python"
      file:
        state: link
        src: "/srv/commdata/matrix/regui/venv_py{{ matreg__pyver.stdout }}"
        dest: "/srv/commdata/matrix/regui/venv"

    - name: "Directory for regui logs"
      file:
        path: /srv/commdata/matrix/regui/logs
        state: directory
        # Logs could contain user info
        mode: u=rwx,g=,o=

    - name: "Configuration for registration app"
      template:
        src: "{{ role_path }}/templates/matrix-registration.yaml.j2"
        dest: /srv/commdata/matrix/regui/config.yaml
      no_log: true # secrets

    - name: "Registration app launcher"
      copy:
        content: |
          #!/bin/bash
          set -eu -o pipefail
          /srv/commdata/matrix/regui/venv/bin/matrix-registration \
            --config-path /srv/commdata/matrix/regui/config.yaml \
            serve \
            >> /srv/commdata/matrix/regui/logs/stdout.log \
            2>> /srv/commdata/matrix/regui/logs/stderr.log
        dest: /srv/commdata/matrix/regui/run.sh
        mode: a+x
      notify: "regui config change"

    - name: "Registration app admin script"
      copy:
        content: |
          #!/bin/bash
          # Make calls to admin API via curl
          set -eu -o pipefail

          if [[ "$#" -lt 1 ]]; then
            echo "Usage: admin.sh /api/... [optional curl args...]"
            exit 1
          fi

          api_path="$1" # e.g. "version"
          shift

          if [[ ! "$api_path" =~ ^/api/.* ]]; then
            echo "Path must start with /api/"
            exit 1
          fi

          curl -sS \
            -H "Authorization: SharedSecret {{ matrix__regui_admin_password }}" \
            "http://localhost:{{ matrix__regui_listen_port }}${api_path}" \
            "$@"
        dest: /srv/commdata/matrix/regui/admin.sh
        mode: u=rwx,g=,o=
      no_log: true # secrets


- name: "Log rotation"
  copy:
    content: |
      /srv/commdata/matrix/regui/logs/stdout.log /srv/commdata/matrix/regui/logs/stderr.log {
          daily
          rotate 20
          missingok
          create 600 matreg matreg
      }
    dest: /etc/logrotate.d/matrix-registration-launcher

- name: "Registration systemd service unit file"
  copy:
    content: |
      [Unit]
      Description=Matrix registration service

      # nginx not listed, since it's not a hard requirement for the
      # process, just the service being reachable.
      Requires=commdata-fs.service
      After=commdata-fs.service

      # If it auto-restarts this many times in this many seconds, stop
      # auto-restarting.
      StartLimitBurst=3
      StartLimitIntervalSec=30

      [Service]
      Type=simple
      ExecStart=/srv/commdata/matrix/regui/run.sh
      User=matreg
      Group=matreg

      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/matrix-registration.service
  register: matrix__regui_service_file

- name: "Reload systemd config if registration unit file changed"
  command: systemctl daemon-reload
  when: matrix__regui_service_file.changed

- name: "Enable registration service"
  service:
    name: matrix-registration
    enabled: yes
    state: started
